controller_list:
  - name: phantom_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - PhantomXPincher_joint1_1
      - PhantomXPincher_joint2_1
      - PhantomXPincher_joint3_1
      - PhantomXPincher_joint4_1
      - PhantomXPincher_gripperCenter_joint_1
  - name: gripper_controller
    action_ns: gripper_cmd
    type: GripperCommand
    joints:
      - PhantomXPincher_gripperClose_joint_1
