vrep:
  walls: [
      80cmHighWall100cm, 80cmHighWall100cm0, 80cmHighWall100cm1, 80cmHighWall100cm2, 80cmHighWall100cm3,
      80cmHighWall100cm4, 80cmHighWall100cm5, 80cmHighWall100cm6, 80cmHighWall100cm7, 80cmHighWall100cm8,

      80cmHighWall200cm, 80cmHighWall200cm0, 80cmHighWall200cm1, 80cmHighWall200cm2, 80cmHighWall200cm3,
      80cmHighWall200cm4, 80cmHighWall200cm5, 80cmHighWall200cm6, 80cmHighWall200cm7, 80cmHighWall200cm8,

      80cmHighWall250cm, 80cmHighWall250cm0, 80cmHighWall250cm1, 80cmHighWall250cm2, 80cmHighWall250cm3,
      80cmHighWall250cm4, 80cmHighWall250cm5, 80cmHighWall250cm6, 80cmHighWall250cm7, 80cmHighWall250cm8,

      80cmHighWall300cm, 80cmHighWall300cm0, 80cmHighWall300cm1, 80cmHighWall300cm2, 80cmHighWall300cm3,
      80cmHighWall300cm4, 80cmHighWall300cm5, 80cmHighWall300cm6, 80cmHighWall300cm7, 80cmHighWall300cm8,

      80cmHighWall500cm, 80cmHighWall500cm0, 80cmHighWall500cm1, 80cmHighWall500cm2, 80cmHighWall500cm3,
      80cmHighWall500cm4, 80cmHighWall500cm5, 80cmHighWall500cm6, 80cmHighWall500cm7, 80cmHighWall500cm8,

      80cmHighWall750cm, 80cmHighWall750cm0, 80cmHighWall750cm1, 80cmHighWall750cm2, 80cmHighWall750cm3,
      80cmHighWall750cm4, 80cmHighWall750cm5, 80cmHighWall750cm6, 80cmHighWall750cm7, 80cmHighWall750cm8,

      80cmHighWall1000cm, 80cmHighWall1000cm0, 80cmHighWall1000cm1, 80cmHighWall1000cm2, 80cmHighWall1000cm3,
      80cmHighWall1000cm4, 80cmHighWall1000cm5, 80cmHighWall1000cm6, 80cmHighWall1000cm7, 80cmHighWall1000cm8,

      80cmHighWall1500cm, 80cmHighWall1500cm0, 80cmHighWall1500cm1, 80cmHighWall1500cm2, 80cmHighWall1500cm3,
      80cmHighWall1500cm4, 80cmHighWall1500cm5, 80cmHighWall1500cm6, 80cmHighWall1500cm7, 80cmHighWall1500cm8,

      80cmHighWall2000cm, 80cmHighWall2000cm0, 80cmHighWall2000cm1, 80cmHighWall2000cm2, 80cmHighWall2000cm3,
      80cmHighWall2000cm4, 80cmHighWall2000cm5, 80cmHighWall2000cm6, 80cmHighWall2000cm7, 80cmHighWall2000cm8,

      240cmHighWall910cm, 240cmHighWall910cm0, 240cmHighWall910cm1, 240cmHighWall910cm2, 240cmHighWall910cm3,
      240cmHighWall910cm4, 240cmHighWall910cm5, 240cmHighWall910cm6, 240cmHighWall910cm7, 240cmHighWall910cm8,

      240cmHighWall750cm, 240cmHighWall750cm0, 240cmHighWall750cm1, 240cmHighWall750cm2, 240cmHighWall750cm3,
      240cmHighWall750cm4, 240cmHighWall750cm5, 240cmHighWall750cm6, 240cmHighWall750cm7, 240cmHighWall750cm8,
      240cmHighWall750cm9, 240cmHighWall750cm10, 240cmHighWall750cm11, 240cmHighWall750cm12, 240cmHighWall750cm13,
      240cmHighWall750cm14, 240cmHighWall750cm15, 240cmHighWall750cm16, 240cmHighWall750cm17, 240cmHighWall750cm18,
      240cmHighWall750cm19, 240cmHighWall750cm20, 240cmHighWall750cm21, 240cmHighWall750cm22, 240cmHighWall750cm23,

      240cmHighWall1000cm, 240cmHighWall1000cm0, 240cmHighWall1000cm1, 240cmHighWall1000cm2, 240cmHighWall1000cm3,
      240cmHighWall1000cm4, 240cmHighWall1000cm5, 240cmHighWall1000cm6, 240cmHighWall1000cm7, 240cmHighWall1000cm8,
      240cmHighWall1000cm9, 240cmHighWall1000cm10, 240cmHighWall1000cm11, 240cmHighWall1000cm12, 240cmHighWall1000cm13,
      240cmHighWall1000cm14, 240cmHighWall1000cm15, 240cmHighWall1000cm16, 240cmHighWall1000cm17, 240cmHighWall1000cm18,
      240cmHighWall1000cm19, 240cmHighWall1000cm20, 240cmHighWall1000cm21, 240cmHighWall1000cm22, 240cmHighWall1000cm23
  ]

  robots: [
      turtlebot2i, turtlebot2i#0, turtlebot2i#1, turtlebot2i#2, turtlebot2i#3, turtlebot2i#4, turtlebot2i#5,
      turtlebot2i#6, turtlebot2i#7, turtlebot2i#8, turtlebot2i#9
  ]

  static_objects: [
      80cmHighPillar100cm, 80cmHighPillar100cm0, 80cmHighPillar100cm1, 80cmHighPillar100cm2, 80cmHighPillar100cm3,
      80cmHighPillar100cm4, 80cmHighPillar100cm5, 80cmHighPillar100cm6, 80cmHighPillar100cm7, 80cmHighPillar100cm8,

      240cmHighPillar100cm, 240cmHighPillar100cm0, 240cmHighPillar100cm1, 240cmHighPillar100cm2, 240cmHighPillar100cm3,
      240cmHighPillar100cm4, 240cmHighPillar100cm5, 240cmHighPillar100cm6, 240cmHighPillar100cm7, 240cmHighPillar100cm8,

      ConcreteBox, ConcreteBox0, ConcreteBox1, ConcreteBox2, ConcreteBox3, ConcreteBox4, ConcreteBox5,
      ConcreteBox6, ConcreteBox7, ConcreteBox8, ConcreteBox9,

      ConcreteBox#0, ConcreteBox#1, ConcreteBox#2, ConcreteBox#3, ConcreteBox#4, ConcreteBox#5,
      ConcreteBox#6, ConcreteBox#7, ConcreteBox#8, ConcreteBox#9, ConcreteBox#10, ConcreteBox#11,
      ConcreteBox#12, ConcreteBox#13, ConcreteBox#14, ConcreteBox#15, ConcreteBox#16, ConcreteBox#17,
      ConcreteBox#18, ConcreteBox#19, ConcreteBox#20, ConcreteBox#21, ConcreteBox#22, ConcreteBox#23,
      ConcreteBox#24, ConcreteBox#25, ConcreteBox#26, ConcreteBox#27, ConcreteBox#28, ConcreteBox#29,
      ConcreteBox#30, ConcreteBox#31, ConcreteBox#32, ConcreteBox#33, ConcreteBox#34, ConcreteBox#35,
      ConcreteBox#36, ConcreteBox#37, ConcreteBox#38, ConcreteBox#39, ConcreteBox#40, ConcreteBox#41,
      ConcreteBox#42, ConcreteBox#43, ConcreteBox#44, ConcreteBox#45, ConcreteBox#46, ConcreteBox#47,

      ConveyorBelt, ConveyorBelt#0, ConveyorBelt#1, ConveyorBelt#2, ConveyorBelt#3, ConveyorBelt#4, ConveyorBelt#5,
      ConveyorBelt#6, ConveyorBelt#7, ConveyorBelt#8, ConveyorBelt#9,

      ShelfBodySimple, ShelfBodySimple#1, ShelfBodySimple#2, ShelfBodySimple#3, ShelfBodySimple#4, ShelfBodySimple#5,
      ShelfBodySimple#6, ShelfBodySimple#7, ShelfBodySimple#8, ShelfBodySimple#9,

      ShelfBody, ShelfBody#1, ShelfBody#2, ShelfBody#3, ShelfBody#4, ShelfBody#5, ShelfBody#6, ShelfBody#7, ShelfBody#8,
      ShelfBody#9,

      dockstation_body, dockstation_body#0, dockstation_body#1, dockstation_body#2, dockstation_body#3,
      dockstation_body#4, dockstation_body#5, dockstation_body#6, dockstation_body#7, dockstation_body#8,
      dockstation_body#9
  ]

  dynamic_objects: [
      Bill, Bill#0, Bill#1, Bill#2, Bill#3, Bill#4, Bill#5, Bill#6, Bill#7, Bill#8, Bill#9, Bill#10,
      Bill#11, Bill#12, Bill#13, Bill#14, Bill#15, Bill#16, Bill#17, Bill#18, Bill#19, Bill#20,

      Walking_Bill, Walking_Bill#0, Walking_Bill#1, Walking_Bill#2, Walking_Bill#3, Walking_Bill#6, Walking_Bill#7,
      Walking_Bill#8, Walking_Bill#9, Walking_Bill#10, Walking_Bill#11, Walking_Bill#12, Walking_Bill#13,
      Walking_Bill#14, Walking_Bill#15, Walking_Bill#16, Walking_Bill#17, Walking_Bill#18, Walking_Bill#19,
      Walking_Bill#20
  ]