network:
  bandwidth: 50       # MHz
  mec_server:
    host: mec_server
    position:         # used only for WiFi
      x: 15
      y: 15
  robots:
    n: 1
  gnb:                # used only for 5G
    position:
      x: 15
      y: 15
  warehouse:
    x_min: -20
    x_max: 20
    y_min: -20
    y_max: 20
    z_min: -1
    z_max: 10         # height of warehouse
    rooms:
      n_x: 4
      n_y: 4