network:
  mec_server:
    host: mec_server        # hostname, only for real network (not used in simulation)
  base_station:
    position: [12.5, 12.5, 0]
  robots:
    n: 1                    # number of robots, must coincide with robots in V-REP
  warehouse:
    boundaries: [-15, 15, -15, 15, -1, 10]
    rooms:
      n_x: 3
      n_y: 3
  congestion:
    data_rate: 3000000      # data rate in on state (bps)
    on_time: [2, 5]         # min and max values for uniform random variable of the 'On' state
    off_time: [5, 10]       # min and max values for uniform random variable of the 'Off' state
    n: 3                    # number of nodes
    position: [             # position of nodes
      [0, 10, 0],
      [-10, -10, 0],
      [-10, 10, 0],
    ]
