network:
  bandwidth: 50             # MHz
  mec_server:
    host: mec_server
  base_station:
    position: [10, 15, 0]
  robots:
    n: 1                    # number of robots, must coincide with robots in V-REP
  warehouse:
    boundaries: [-15, 15, -20, 20, -1, 10]
    rooms:
      n_x: 3
      n_y: 4
  congestion:
    data_rate: 2000000      # data rate in on state (bps)
    switch_time:
      min: 1                # min time in on/off state before switching (s)
      max: 5                # max time in on/off state before switching (s)
    n: 4                    # number of nodes
    position: [             # position of nodes
      [10, 5, 0],
      [-10, 5, 0],
      [0, -5, 0],
      [0, 15, 0],
    ]