pick_and_place:
  goals:
    pick: [
      # waypoints of shelves
      [-7, 12.513, 0.063],
      [-3, 12.513, 0.063],
      [-13, 2.513, 0.063],
      [-3, 2.513, 0.063],
      [-13, -2.513, 0.063],
      [3, -2.513, 0.063],
      [13, -2.513, 0.063],
    ]
    place: [
      # waypoints of conveyor belts
      [-10, -17.9, 0.063],
      [0, -17.9, 0.063],
      [10, -17.9, 0.063],
    ]