pick_and_place:
  goals:
    pick: [
      # waypoints of shelves
      [-12, 7.487],
      [-8, 12.513],
      [-12, 12.513],
      [-18, -2.513],
      [2, 2.513],
      [-8, 2.513],
      [2, -2.513],
      [-8, -2.513]
    ]
    place: [
      # waypoints of conveyor belts
      [-15, -17.9],
      [-5, -17.9],
      [5, -17.9],
      [15, -17.9]
    ]