pick_and_place:
  goals:
    pick: [
      # waypoints of shelves
      [-7, 7.513, 0.063],
      [3, 7.513, 0.063],
      [-7, 2.487, 0.063],
      [3, 2.487, 0.063],
      [7, 2.487, 0.063],
    ]
    place: [
      # waypoints of conveyor belts
      [-10, -12.9, 0.063],
      [0, -12.9, 0.063],
      [10, -12.9, 0.063],
    ]
