rl:
  robot:
    compute_power: 10       # 10 W, see https://askgeek.io/en/cpus/Intel/Celeron-J3455
    transmit_power: 0.1     # 100 mW, transmit power of WiFi at 2.4 GHz, see https://metis.fi/en/2017/10/txpower/
  reward:
    w_latency: 1
    w_energy: 0
  goals: [
    [ -9.0, 6.5 ],
    [ -9.0, 3.0 ],
    [ -4.0, 6.5 ],
    [ -4.0, 3.0 ],
    [ -0.5, 6.0 ],
    [ 1.0, 3.0 ],
    [ 5.0, 2.5 ],
    [ 3.0, 0.0 ],
    [ -8.5, 0.0 ],
    [ -0.5,-2.0 ],
    [ 9.0,-6.5 ],
    [ 5.0,-2.0 ],
    [ -4.5,-2.5 ],
    [ 8.5,-0.5 ],
    [ -9.0,-6.5 ]
  ]