rl:
  robot:
    compute_power: 1        # Watt
    transmit_power: 0.1     # Watt
  reward:
    w_latency: 0.33
    w_energy: 0.33
    w_model: 0.33
  goals: [
    [ -9.0, 6.5 ],
    [ -9.0, 3.0 ],
    [ -4.0, 6.5 ],
    [ -4.0, 3.0 ],
    [ -0.5, 6.0 ],
    [ 1.0, 3.0 ],
    [ 5.0, 2.5 ],
    [ 3.0, 0.0 ],
    [ -8.5, 0.0 ],
    [ -0.5,-2.0 ],
    [ 9.0,-6.5 ],
    [ 5.0,-2.0 ],
    [ -4.5,-2.5 ],
    [ 8.5,-0.5 ],
    [ -9.0,-6.5 ]
  ]