version: '3.3'

services:
  planner_reasoner:
    image: scott-planner-reasoner
    environment:
      - PORT=3020 # internal port
    ports:
      - "3021:3020" # mapping of external port to internal port
    stdin_open: true
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker]
      restart_policy:
        condition: on-failure
  sandbox-whc:
    image: scott-webapp-whc
    networks:
      - overlay
  ports:
    - "8080:8080"
    deploy:
       replicas: 2
       placement:
        constraints: [node.role == worker]
       restart_policy:
         condition: on-failure
    depends_on:
    - warehouse-fuseki
    - mosquitto
  sandbox-twin:
    image: scott-webapp-twin
    networks:
      - overlay
  ports:
     - "8081:8080"
    deploy:
       replicas: 2
       placement:
        constraints: [node.role == worker]
       restart_policy:
         condition: on-failure
    depends_on:
    # - sandbox-whc
    - mosquitto
  robot-emulator:
    # 'ContainerSpec: image reference must be provided'
    image: scott-robot-emulator
    networks:
      - overlay
    deploy:
       replicas: 2
       placement:
        constraints: [node.role == worker]
       restart_policy:
         condition: on-failure
    depends_on:
      # - sandbox-twin
      - mosquitto
  # sandbox-twin-shelf:
  #   build: ../webapp-twin-shelf
  #   ports:
  #    - "8082:8080"
  #   depends_on:
  #   - sandbox-whc
  #   - mosquitto
  #   networks:
  #     - overlay
  warehouse-fuseki:
    image: stain/jena-fuseki
  networks:
      - overlay
    ports:
     - "3030:3030"
    volumes:
      - ./fuseki_config:/fuseki/configuration
  deploy:
       replicas: 1
       placement:
        constraints: [node.role == worker]
       restart_policy:
         condition: on-failure
  mosquitto:
    image: eclipse-mosquitto
  networks:
      - overlay
    ports:
     - 1883
     - 9001
  deploy:
       replicas: 1
       placement:
        constraints: [node.role == worker]
       restart_policy:
         condition: on-failure

networks:
  overlay:
