version: '3.3'

services:
  sandbox-whc:
    build: ../webapp-whc
    ports:
    - "8080:8080"
    depends_on:
    - warehouse-fuseki
    - mosquitto
    networks:
      - overlay
  sandbox-twin:
    build: ../webapp-twin
    ports:
     - "8081:8080"
    depends_on:
    - sandbox-whc
    - mosquitto
    networks:
      - overlay
  sandbox-twin-shelf:
    build: ../webapp-twin-shelf
    ports:
     - "8082:8080"
    depends_on:
    - sandbox-whc
    - mosquitto
    networks:
      - overlay
  warehouse-fuseki:
    image: stain/jena-fuseki
    ports:
     - "3030:3030"
    volumes:
      - ./fuseki_config:/fuseki/configuration
    networks:
      - overlay
  mosquitto:
    image: eclipse-mosquitto
    ports:
     - 1883
     - 9001
    networks:
      - overlay

networks:
  overlay: