# See http://wiki.ros.org/turtlebot_navigation/Tutorials/indigo/Setup%20the%20Navigation%20Stack%20for%20TurtleBot

TrajectoryPlannerROS:
  min_vel_x: 0.05

  yaw_goal_tolerance: 1.57      # 90 degrees, we don't care about the yaw
  xy_goal_tolerance: 0.5

  path_distance_bias: 0.4       # weighting for how much it should stick to the global path plan
  goal_distance_bias: 0.8       # weighting for how much it should attempt to reach its goal
  occdist_scale: 0.01           # weighting for how much the controller should attempt to avoid obstacles
  publish_cost_grid_pc: false   # true only for tuning pdist_scale, gdist_scale and occdist_scale, cost grid in rviz

  holonomic_robot: false
  meter_scoring: true


# Adapted from https://github.com/turtlebot/turtlebot_apps/tree/indigo/turtlebot_navigation/param
# Warning!
#   this does not work correctly because of odometry computation
#   see https://github.com/ros-planning/navigation/issues/927

DWAPlannerROS:
  # Robot Configuration Parameters - Kobuki
  # Warning!
  #   do not set min_trans_vel to 0.0 otherwise dwa will always think translational velocities
  #   are non-negligible and small in place rotational velocities will be created.
  max_vel_x: 0.7
  min_vel_x: 0.0
  max_vel_y: 0.0                # diff drive robot
  min_vel_y: 0.0                # diff drive robot
  max_vel_trans: 0.5            # choose slightly less than the base's capability
  min_vel_trans: 0.1            # this is the min trans velocity when there is negligible rotational velocity
  trans_stopped_vel: 0.1
  max_vel_theta: 3.14           # choose slightly less than the base's capability
  min_vel_theta: 0.4            # this is the min angular velocity when there is negligible translational velocity
  theta_stopped_vel: 0.4
  acc_lim_x: 1.0                # maximum is theoretically 2.0, but we
  acc_lim_theta: 2.0
  acc_lim_y: 0.0                # diff drive robot
  holonomic_robot: false

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 1.57      # 90 degrees, we don't care about the yaw
  xy_goal_tolerance: 0.5

  # Forward Simulation Parameters
  sim_time: 1.0
  vx_samples: 6
  vy_samples: 1                 # diff drive robot, there is only one sample
  vtheta_samples: 20

  # Trajectory Scoring Parameters
  path_distance_bias: 64.0      # weighting for how much it should stick to the global path plan
  goal_distance_bias: 24.0      # weighting for how much it should attempt to reach its goal
  occdist_scale: 0.5            # weighting for how much the controller should avoid obstacles
  forward_point_distance: 0.325 # how far along to place an additional scoring point
  stop_time_buffer: 0.2         # amount of time a robot must stop in before colliding for a valid traj.
  scaling_speed: 0.25           # absolute velocity at which to start scaling the robot's footprint
  max_scaling_factor: 0.2       # how much to scale the robot's footprint when at speed.

  # Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05  # how far to travel before resetting oscillation flags

  # Debugging
  publish_traj_pc : false
  publish_cost_grid_pc: false
  global_frame_id: odom
