obstacle_range: 2.5
raytrace_range: 3.0
#footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
robot_radius: 0.2
inflation_radius: 0.4 #0.15
cost_scaling_factor: 10
transform_tolerance: 10.0 # 10 second
#publish_voxel_map: true

#observation_sources: laser_scan_sensor
#laser_scan_sensor: {sensor_frame: turtlebot2i/lidar/scan, data_type: LaserScan, topic: /turtlebot2i/lidar/scan, marking: true, clearing: true}

plugins:
  - {name: obstacle_layer, type: "costmap_2d::VoxelLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
  - {name: static_layer, type: "costmap_2d::StaticLayer"}


obstacle_layer:
  observation_sources: laser_scan_sensor
  laser_scan_sensor: {sensor_frame: turtlebot2i/lidar/scan, data_type: LaserScan, topic: /turtlebot2i/lidar/scan, marking: true, clearing: true}
