#plugins: 
#    - {name: obstacles,        type: "costmap_2d::ObstacleLayer"}
#    - {name: static_map,       type: "costmap_2d::StaticLayer"}
#    - {name: inflation_layer,  type: "costmap_2d::InflationLayer"}
#obstacles:
#    observation_sources: base_scan
#    base_scan: {data_type: LaserScan, sensor_frame: turtlebot2i/lidar/scan, clearing: true, marking: true, topic: /turtlebot2i/lidar/scan}
#    obstacle_range: 2.5
#    raytrace_range: 3.0
#inflation_layer:
#    inflation_radius: 0.25 #0.15 #
#    cost_scaling_factor: 5
publish_frequency: 10
transform_tolerance: 10 # second
robot_radius: 0.25

