# Adapted from https://github.com/turtlebot/turtlebot_apps/tree/indigo/turtlebot_navigation/param
# See also https://wiki.ros.org/navigation/Tutorials/Navigation%20Tuning%20Guide

global_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 1.0
  publish_frequency: 0.5    # for visualization in rviz
  width: 50.0
  height: 50.0

  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}     # not voxel, we just have a LiDAR
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  inflation_layer:
    inflation_radius: 0.4