global_costmap:
 plugins: 
     - {name: static_map,       type: "costmap_2d::StaticLayer"}
     - {name: obstacles_glb,        type: "costmap_2d::ObstacleLayer"}
     - {name: inflation_layer_glb,  type: "costmap_2d::InflationLayer"}
 obstacles_glb:
     observation_sources: base_scan
     base_scan: {data_type: LaserScan, sensor_frame: turtlebot2i/lidar/scan, clearing: true, marking: true, topic: /turtlebot2i/lidar/scan}
     obstacle_range: 2.5
     raytrace_range: 3.0
 inflation_layer_glb:
     inflation_radius: 0.4
     cost_scaling_factor: 10
 global_frame: map
 robot_base_frame: turtlebot2i/base_footprint
 update_frequency: 5 #10
 rolling_window: true
 width: 40.0
 height: 40.0
 resolution: 0.05
