# Adapted from https://github.com/turtlebot/turtlebot_apps/tree/indigo/turtlebot_navigation/param

local_costmap:
  global_frame: odom
  robot_base_frame: base_footprint
  update_frequency: 5.0
  publish_frequency: 1.0    # for visualization in rviz
  rolling_window: true
  width: 10.0
  height: 10.0

  plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}   # to avoid taking shortcuts through walls
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  inflation_layer:
    inflation_radius: 0.2