controller_frequency: 5.0
controller_patience: 10.0
planner_patience: 10.0
oscillation_timeout: 10.0
oscillation_distance: 0.2
base_local_planner: base_local_planner/TrajectoryPlannerROS   # alternative: dwa_local_planner/DWAPlannerROS